TEST_web/urls.py
from django.contrib import admin
from django.urls import path, include
from api.urls import api

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('archive/', include('archive.urls')),
    path('catalog/', include('catalog.urls')),
    path('main/', include('main.urls')),
    path('camera/', include('camera.urls')),
    path('filter_wheel/', include('filter_wheel.urls')),
    path('observation/', include('observation.urls')),
    path('settings/', include('settings.urls')),
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
    path('api/', api.urls)
]

api/urls.py
from ninja import NinjaAPI, Router
from main.api import router as main_router
from mount.api import router as mount_router
from camera.api import router as camera_router

api = NinjaAPI()

router_v1 = Router()
router_v1.add_router('', main_router)
router_v1.add_router('mount/', mount_router)
router_v1.add_router('camera/', camera_router)
api.add_router('v1', router_v1)

archive/urls.py
from django.urls import path

from . import views

app_name = 'archive'

urlpatterns = [
    path('', views.ImageTableView.as_view(), name='index'),
]

camera/urls.py
from django.urls import path

from . import views

app_name = 'camera'
urlpatterns = [
]

catalog/urls.py
from django.urls import path

from . import views

app_name = 'catalog'

urlpatterns = [
    path('', views.SourceTableView.as_view(), name='index'),
    path('add/', views.SourceFormView.as_view(), name='add'),
    path('source_types/', views.SourceTypeTableView.as_view(), name='source_types'),
    path('source_types/add/', views.SourceTypeFormView.as_view(), name='source_types_add'),
]

filter_wheel/urls.py
from django.urls import path

from . import views

app_name = 'filter_wheel'
urlpatterns = [
    path('', views.FilterTableView.as_view(), name='index'),
    path('add/', views.FilterFormView.as_view(), name='add')
]

main/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

observation/urls.py
from django.urls import path

from . import views

app_name = 'observation'

urlpatterns = [
    path('', views.ObservationTableView.as_view(), name='index'),
    path('standard/', views.ObservationFormView.as_view(), name='standard'),
    path('catalog/', views.ObservationCatalogFormView.as_view(), name='catalog')
]

settings/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

api/models.py
from django.db import models

# Create your models here.

archive/models.py
from django.db import models
from django.contrib.auth.models import User
from catalog.models import Source
from filter_wheel.models import Filter
# Create your models here.


class ImageTye(models.Model):
    name = models.CharField(max_length=100)


class Image(models.Model):
    target = models.ForeignKey(Source, models.SET_NULL, null=True)
    filter = models.ForeignKey(Filter, models.SET_NULL, null=True)
    type = models.ForeignKey(ImageTye, on_delete=models.SET_NULL, null=True)

    exposure_time = models.FloatField()
    exposure_started = models.DateTimeField()

    observer = models.ForeignKey(User, models.SET_NULL, null=True)

    fits_file = models.FileField(null=True, upload_to='uploads/%Y/%m/%d/')

    def __str__(self):
        target_name = self.target.name if self.target else ''
        return f'{target_name} (started at {self.exposure_started} with exposure time of {self.exposure_time})'

camera/models.py
from django.db import models
from datetime import datetime
# Create your models here.


class Camera(models.Model):
    device_number = models.PositiveSmallIntegerField()


class Monitoring(models.Model):
    date = models.DateTimeField(auto_now_add=datetime.utcnow)
    temperature = models.FloatField()
    camera = models.ForeignKey(Camera, on_delete=models.SET_NULL, null=True)


class Tracker(models.Model):
    action = models.CharField(max_length=100)
    date = models.DateTimeField(auto_now_add=datetime.utcnow)

catalog/models.py
from django.db import models

# Create your models here.


class SourceType(models.Model):
    name = models.CharField(max_length=100)
    periodic = models.BooleanField()


class Source(models.Model):
    name = models.CharField(max_length=100)
    ra = models.FloatField()
    dec = models.FloatField()

    type = models.ForeignKey(SourceType, models.SET_NULL, null=True)

    def __str__(self):
        return self.name

dome/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models

# Create your models here.

mount/models.py
from django.db import models

# Create your models here.

catalog/forms.py
from django import forms

from .models import Source, SourceType


class SourceForm(forms.ModelForm):
    class Meta:
        model = Source
        fields = '__all__'


class SourceTypeForm(forms.ModelForm):
    class Meta:
        model = SourceType
        fields = '__all__'

api/views.py
from django.shortcuts import render

# Create your views here.

archive/views.py
from django.shortcuts import render
from django_tables2 import SingleTableView
from .tables import ImageTable
from .models import Image
# Create your views here.

from django.http import HttpResponse


class ImageTableView(SingleTableView):
    table_class = ImageTable
    template_name = 'archive/index.html'
    model = Image

camera/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, FormView
from django.urls import reverse_lazy

from . import tasks

catalog/views.py
from django.shortcuts import render
from django.views.generic import FormView
from django_tables2 import SingleTableView
# Create your views here.
from .models import Source, SourceType
from .forms import SourceTypeForm, SourceForm
from .tables import SourceTable, SourceTypeTable

from django.http import HttpResponse


def index(request):
    return HttpResponse("Hello, world. You're at the polls index.")


class SourceTableView(SingleTableView):
    template_name = 'catalog/index.html'
    table_class = SourceTable
    model = Source


class SourceTypeTableView(SingleTableView):
    template_name = 'catalog/index.html'
    table_class = SourceTypeTable
    model = SourceType


class SourceFormView(FormView):
    form_class = SourceForm
    template_name = 'catalog/form.html'


class SourceTypeFormView(FormView):
    form_class = SourceTypeForm
    template_name = 'catalog/form.html'

dome/views.py
from django.shortcuts import render

# Create your views here.

main/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse


def index(request):
    content = {'section': 'main',
               'title': 'Index'}
    return render(request, 'main/index.html', context=content)

mount/views.py
from django.shortcuts import render

# Create your views here.

settings/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse


def index(request):
    return HttpResponse("Hello, world. You're at the polls index.")

archive/templates/archive/form.html
{% extends 'main/basic.html' %}

{% block container %}
    <form method="post">
        <table>
            {{ form.as_table }}
        </table>
    </form>
{% endblock %}

archive/templates/archive/index.html
{% extends 'main/basic.html' %}

{% block container %}
        {% load render_table from django_tables2 %}
        {% render_table table %}
{% endblock %}

archive/templates/archive/nav.html
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Archive
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        <a class="dropdown-item active" href="{% url 'archive:index' %}">Overview</a>
    </div>
</li>

camera/templates/camera/form.html
{% extends 'main/basic.html' %}

{% block container %}
    <form method="post">
        <table>
            {{ form.as_table }}
        </table>
    </form>
{% endblock %}

camera/templates/camera/nav.html
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Camera
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        <a class="dropdown-item active" href="observation/">Overview</a>
    </div>
</li>

camera/templates/something/form.html
{% extends 'main/basic.html' %}

{% block container %}
    <form method="post">
        <table>
            {{ form.as_table }}
        </table>
    </form>
{% endblock %}

camera/templates/something/nav.html
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Archive
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        <a class="dropdown-item active" href="{% url 'archive:index' %}">Overview</a>
    </div>
</li>

main/templates/main/basic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'local/panel.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'semantic.css' %}">
    <script src="{% static 'semantic.js' %}"></script>
    <title>{{title}}</title>
    {% block header %}
    {% endblock %}
</head>
<body>
{% include 'main/navbar.html' %}
{% block prebody %}
{% endblock %}
<div style="margin:1%" class="container-lg">
    {% block body %}
    {% endblock %}
</div>

        <div class="ui container" style="padding-left: 5vw">

            {% block container %}
            {% endblock %}
        </div>
</body>
</html>

main/templates/main/index.html
{% extends 'main/basic.html' %}

main/templates/main/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
        {% ifequal section 'main' %}
            <li class="nav-item active">
        {% else %}
            <li class="nav-item">
        {% endifequal %}

        <a class="nav-link" href="#">Home</a>
      </li>
      {% include 'observation/nav.html' %}
      {% include 'camera/nav.html' %}
        {% include 'archive/nav.html' %}
        {% include 'filter_wheel/nav.html' %}
        {% include 'catalog/nav.html' %}
      <li class="nav-item">
        <a class="nav-link" href="#">Settings</a>
      </li>
      <li class="nav-item">
      </li>
    </ul>
  </div>
</nav>