TEST_web/urls.py
from django.contrib import admin
from django.urls import path, include
from api.urls import api

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('archive/', include('archive.urls')),
    path('catalog/', include('catalog.urls')),
    path('main/', include('main.urls')),
    path('camera/', include('camera.urls')),
    path('filter_wheel/', include('filter_wheel.urls')),
    path('observation/', include('observation.urls')),
    path('settings/', include('settings.urls')),
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
    path('api/', api.urls)
]

api/urls.py
from ninja import NinjaAPI, Router
from main.api import router as main_router
from mount.api import router as mount_router
from camera.api import router as camera_router

api = NinjaAPI()

router_v1 = Router()
router_v1.add_router('', main_router)
router_v1.add_router('mount/', mount_router)
router_v1.add_router('camera/', camera_router)
api.add_router('v1', router_v1)

observation/urls.py
from django.urls import path

from . import views

app_name = 'observation'

urlpatterns = [
    path('', views.ObservationTableView.as_view(), name='index'),
    path('standard/', views.ObservationFormView.as_view(), name='standard'),
    path('catalog/', views.ObservationCatalogFormView.as_view(), name='catalog')
]

observation/models.py
from django.db import models
from datetime import datetime
from catalog.models import Source
from filter_wheel.models import Filter
from django.contrib.auth.models import User
# Create your models here.


class ObservationList(models.Model):
    name = models.CharField(max_length=100)

    created = models.DateTimeField(auto_created=datetime.utcnow)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    flats = models.IntegerField(default=10)
    darks = models.IntegerField(default=10)

    done = models.BooleanField(default=False)


class Observation(models.Model):
    started = models.DateTimeField()
    ended = models.DateTimeField()
    observation_list = models.ForeignKey(ObservationList, on_delete=models.CASCADE,)
    target = models.ForeignKey(Source, on_delete=models.SET_NULL, null=True)
    filter = models.ForeignKey(Filter, on_delete=models.SET_NULL, null=True)

    exposure_time = models.IntegerField()

observation/forms.py
from django import forms
from filter_wheel.models import Filter
from catalog.models import Source


class ObservationForm(forms.Form):
    name = forms.CharField(max_length=100)
    filter = forms.ModelChoiceField(queryset=Filter.objects.all())

    exposure_time = forms.IntegerField(widget=forms.NumberInput(attrs={'min': 0, 'max': 600, 'steps': 1}))


class ObservationCatalogForm(forms.Form):
    target = forms.ModelChoiceField(queryset=Source.objects.all())
    filter = forms.ModelChoiceField(queryset=Filter.objects.all())

    exposure_time = forms.IntegerField(widget=forms.NumberInput(attrs={'min': 0, 'max': 600, 'steps': 1}))

observation/views.py
from django.views.generic import TemplateView, FormView
from django.urls import reverse_lazy
from django_tables2 import SingleTableView
# Create your views here.
from .forms import ObservationForm, ObservationCatalogForm
from .boards.visibility_chart.main import app as visibility_app
from .tables import ObservationTable, Observation


class ObservationFormView(FormView):
    form_class = ObservationForm
    template_name = 'observation/form.html'
    success_url = reverse_lazy('observation:index')


class ObservationCatalogFormView(FormView):
    form_class = ObservationCatalogForm
    template_name = 'observation/form_catalog.html'
    success_url = reverse_lazy('observation:index')


class ObservationTableView(SingleTableView):
    table_class = ObservationTable
    template_name = 'observation/index.html'
    model = Observation

observation/templates/observation/calibration.html
{% extends 'main/basic.html' %}

{% block body %}
<section>
    Astrometry/ Pointing offset
    <form>
        <table>
            <tr>
                <td colspan="2">

                </td>
                
            </tr>
        </table>
    </form>
</section>

<section>
    Photometric
    <form>
        <table>
            <tr>
                <td colspan="2">

                </td>
            </tr>
            <tr>
                <td>
                    Survey:
                </td>
                <td>
                    <select>
                        {% for s in surveys %}
                            <option value="{{s}}">
                                {{s}}
                            </option>
                        {% endfor %}
                    </select>
                </td>
            </tr>
            <tr>
                <td>
                    Transformation equation:
                </td>
                <td>
                    <input type="text">
                </td>
            </tr>
        </table>
    </form>
</section>
{% endblock %}

observation/templates/observation/form.html
{% extends 'main/basic.html' %}


{% block container %}
    <form method="post">
        <table>
            {{ form.as_table }}
        </table>
    </form>
{% endblock %}

observation/templates/observation/form_catalog.html
{% extends 'main/basic.html' %}


{% block container %}
    <div class="ui segments">
        <div class="segment">

            <form method="post">
                <table>
                    {{ form.as_table }}
                </table>
            </form>
        </div>
        <div class="segment">
            <h3> second column</h3>
        </div>
        <div class="segment">
            <h3> second column</h3>
        </div>
    </div>
{% endblock %}

observation/templates/observation/index.html
{% extends 'main/basic.html' %}

{% block prebody %}
        {% include 'observation/panel.html' %}
{% endblock %}
{% block container %}
        {% load render_table from django_tables2 %}
        {% render_table table %}
{% endblock %}

observation/templates/observation/nav.html
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Observation
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        <a class="dropdown-item" href="{% url 'observation:index' %}">Overview</a>
        <a class="dropdown-item" href="{% url 'observation:standard' %}">Standard</a>
        <a class="dropdown-item" href="{% url 'observation:catalog' %}">Catalog source</a>
        <a class="dropdown-item" href="{% url 'observation:index' %}">Series</a>
        <a class="dropdown-item" href="{% url 'observation:index' %}">Multi Filter</a>
        <a class="dropdown-item" href="{% url 'observation:index' %}">Calibration</a>
    </div>
</li>

observation/templates/observation/panel.html
{% block header %}
    {% load static %}
    <script src="{% static 'local/panel.js' %}"></script>
{% endblock %}

<div class="ui left fixed vertical menu" style="top: 10vh; height: 90vh">
    {% include 'observation/panel/time.html' %}
    {% include 'observation/panel/telescope.html' %}
    {% include 'observation/panel/camera.html' %}
    {% include 'observation/panel/dome.html' %}
</div>